/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログイン
         * @description メールアドレスとパスワードで認証し、セッションを発行する（ApiDesign.md 3.1）。
         *
         *     応答本文は `GET /api/v1/me` と同じ内容を含む。ログイン直後に必ず権限が必要になるため、
         *     往復を1回減らしている。
         *
         *     認証不要。IPあたり 10回/分のレート制限が掛かる（ApiDesign.md 2.9）。
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログアウト
         * @description 現在のセッショントークンを失効させ（`revoked_at` を設定）、Cookie を削除する
         *     （ApiDesign.md 3.2）。Cookie 認証のため `X-PB-CSRF` が必要（2.4）。
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 自分自身と実効権限
         * @description 認証中のアクターと実効権限を返す（ApiDesign.md 4.1）。
         *
         *     `permissions` はシステムロール由来の実効権限、`projects[].permissions` は
         *     当該プロジェクトでの実効権限（システムロール ∪ プロジェクトロール ∩ スコープ。
         *     Design.md 6.4.1）。`projects[]` にはアーカイブ済みのプロジェクトも含む。
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * プロジェクト一覧
         * @description 自分がメンバーであるプロジェクトを返す。アドミニストレータは全件（ApiDesign.md 5.1）。
         *
         *     **必要権限は `project.view`。** ただしこの権限は「どのプロジェクトが見えるか」を
         *     決めない（オペレータもシステムロールとして持つ）。可視範囲はメンバーシップで絞る。
         *
         *     `ticket_count` / `closed_count` / `progress` を含めるのは、プロジェクトごとに
         *     件数を問い合わせる N+1 を避けるためである（5.1）。
         */
        get: operations["listProjects"];
        put?: never;
        /**
         * プロジェクトの作成
         * @description プロジェクトを作成する（ApiDesign.md 5.3）。必要権限は `project.create`
         *     （Phase 1 = アドミニストレータのみ）。
         *
         *     サーバ側は `project` 作成・`project_counter` 初期化・テンプレートからの
         *     ワークフロー複製・作成者の `project_admin` 登録・`audit_log` への記録を
         *     **単一トランザクション**で行う。
         *
         *     キー重複の検出はDBの `UNIQUE` 制約に委ねる（`check-key` の結果は信頼しない）。
         */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/check-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * プロジェクトキーの利用可否
         * @description 新規作成モーダルの即時検証に使う（ApiDesign.md 5.2）。
         *
         *     判定の順は 形式 → 予約語 → 既存。**この結果は作成時の重複検出には使わない**
         *     （5.3。競合検出はDBの `UNIQUE` 制約に委ねる）。
         *
         *     必要権限は作成と同じ `project.create`。
         */
        get: operations["checkProjectKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description プロジェクトキー（ULID ではない。ApiDesign.md 5.4）。URL・チケット番号と
                 *     一致させ、開発時のデバッグを容易にするため。
                 */
                key: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        /**
         * プロジェクトの詳細
         * @description 1プロジェクトの本体・ワークフロー・メンバー・自分の実効権限を返す
         *     （ApiDesign.md 5.4）。必要権限は `project.view`。
         *
         *     **メンバーでなければ 404**（403 ではない。Design.md 6.4.5）。403 で返すと
         *     「そのキーのプロジェクトは在る」と漏れ、キーを変えながら叩けば
         *     プロジェクトの一覧を復元できてしまう。アドミニストレータは全件に到達できる。
         *
         *     `my_permissions` は認可ミドルウェアと同じ集合から作る
         *     （( システムロール ∪ プロジェクトロール ) ∩ スコープ。Design.md 6.4.1）。
         */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * プロジェクトの更新
         * @description `name` / `description` / `settings` を更新する（ApiDesign.md 5.5）。
         *     必要権限は `project.edit`。
         *
         *     **送られたフィールドだけを更新する**（部分更新）。`"description": null` は
         *     「説明を消す」であり、`description` を送らない（据え置く）とは区別する。
         *
         *     **`key` は変更できない。** 送られた場合は 422 で、`details[].code` が
         *     `immutable_field` になる（`error.code` は `validation_failed`）。
         *
         *     **`If-Match` は必須**（2.8）。省略すると 422（`details[].field` が
         *     `If-Match`）、現在の `version` と食い違えば 409。成功すると `version` が +1 される。
         */
        patch: operations["updateProject"];
        trace?: never;
    };
    "/api/v1/projects/{key}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description プロジェクトキー（ULID ではない。ApiDesign.md 5.4）。URL・チケット番号と
                 *     一致させ、開発時のデバッグを容易にするため。
                 */
                key: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * プロジェクトのアーカイブ
         * @description `status` を `archived` にし、`archived_at` に現在時刻を入れる
         *     （ApiDesign.md 5.6）。必要権限は `project.archive`。
         *
         *     リクエスト本文は取らない。**`If-Match` は要求しない**（2.8）。冪等であり、
         *     競合しても失われる編集内容がないためである。ただし `version` は +1 する。
         *
         *     **既にアーカイブ済みなら何も変えずに 200 を返す。** そのとき `version` は
         *     進まず、監査ログにも残さない（空振りで本当の切り替えが埋もれるため）。
         *
         *     監査は `project.archive` として記録し、`detail.status` で unarchive と区別する。
         */
        post: operations["archiveProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{key}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description プロジェクトキー（ULID ではない。ApiDesign.md 5.4）。URL・チケット番号と
                 *     一致させ、開発時のデバッグを容易にするため。
                 */
                key: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * プロジェクトのアーカイブ解除
         * @description `status` を `active` に戻し、`archived_at` を `null` にする
         *     （ApiDesign.md 5.6）。archive と同じ経路を通り、渡す `status` だけが違う。
         *
         *     必要権限・冪等性・監査の扱いは archive と同じ。
         */
        post: operations["unarchiveProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ユーザー一覧
         * @description 人間とエージェントを同じ一覧に返す（ApiDesign.md 6.1、DbDesign.md 6.2 の
         *     `actor` 統合設計）。**必要権限は `user.manage`**（Phase 1 = アドミニストレータのみ）。
         *
         *     `kind` によって意味を持たないフィールドは `null` を返し、フィールド自体を
         *     省略しない。**`agent` は Phase 1 では常に `null`**（中身にあたる
         *     `agent` テーブルは Phase 2 で作られる）。
         *
         *     `kind = 'system'` の actor は返さない。
         *
         *     `project_count` は `project_member` の行数で、アーカイブ済みプロジェクトも数える。
         */
        get: operations["listUsers"];
        put?: never;
        /**
         * ユーザーの作成
         * @description ユーザーを作成する（ApiDesign.md 6.2）。必要権限は `user.manage`。
         *
         *     サーバ側は `actor` → `app_user` → `user_identity`（`provider_key='local'`,
         *     `subject=email`）→ `local_credential` と `audit_log` への記録を
         *     **単一トランザクション**で行う（DbDesign.md 6.2）。
         *
         *     メール重複の検出はDBの `UNIQUE` 制約に委ねる。
         *
         *     **`generated_password` はこの応答でのみ返る。** 再表示できず、監査ログにも残さない。
         */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthcheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ヘルスチェック
         * @description 監視・オーケストレータ用（ApiDesign.md 2.11）。**唯一 `/api/v1` の外にある。**
         *     認証・CSRF・レート制限・認可の対象外で、DBへは接続しない。
         */
        get: operations["healthcheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            /** @example tanaka@example.com */
            email: string;
            /** Format: password */
            password: string;
        };
        /** @description `POST /auth/login` と `GET /me` が返す共通の本体。**片方だけ形を変えない。** */
        Session: {
            actor: components["schemas"]["Actor"];
            /**
             * @description システムロール由来の実効権限。権限0件は空配列で表す。
             * @example [
             *       "project.view",
             *       "ticket.view"
             *     ]
             */
            permissions: string[];
            /** @description 所属プロジェクトと、そこでの実効権限。`key` の昇順。 */
            projects: components["schemas"]["SessionProject"][];
            /**
             * Format: date-time
             * @description 現在のトークンの有効期限。無期限の API トークンでは null。
             */
            expires_at: string | null;
        };
        Actor: {
            /**
             * @description ULID 26文字。
             * @example 01K2F8QW3H7YRJ4M5N6P7Q8R9S
             */
            id: string;
            /** @enum {string} */
            kind: "user" | "agent";
            display_name: string;
            /** @description エージェントは null（ApiDesign.md 6.1。フィールド自体は省略しない）。 */
            email: string | null;
            /**
             * @description 同上。
             * @enum {string|null}
             */
            system_role: "administrator" | "operator" | null;
            /** @example ja */
            locale: string | null;
            /** @example Asia/Tokyo */
            timezone: string | null;
            /** @description true のときフロントはパスワード変更画面へ誘導する（ApiDesign.md 3.1）。 */
            must_change_password: boolean;
        };
        SessionProject: {
            id: string;
            /** @example my-app */
            key: string;
            name: string;
            /**
             * @description プロジェクトロールのキー（DbDesign.md 7.3）。
             * @example project_admin
             */
            role: string;
            /** @description 当該プロジェクトでの実効権限。 */
            permissions: string[];
        };
        /** @description 一覧の共通エンベロープ（ApiDesign.md 2.6）。 */
        UserList: {
            items: components["schemas"]["UserListItem"][];
            page: number;
            per_page: number;
            total: number;
            /** @description 切り上げ。総件数0のときは0。 */
            total_pages: number;
        };
        /**
         * @description 一覧の1行（ApiDesign.md 6.1）。**`kind` によって意味を持たないフィールドは
         *     `null` を返し、フィールド自体を省略しない。** フロントの分岐を単純にするため。
         */
        UserListItem: {
            /** @description ULID（`actor.id`）。 */
            id: string;
            /** @enum {string} */
            kind: "user" | "agent";
            display_name: string;
            /** @description エージェントは `null`。 */
            email: string | null;
            /**
             * @description エージェントは `null`。
             * @enum {string|null}
             */
            system_role: "operator" | "administrator" | null;
            /**
             * @description **Phase 1 では常に `null`。** 中身（`client_kind` / `model_name` /
             *     `project_key` / `trust_level`）は DbDesign.md 8.1 の `agent` テーブルの列で、
             *     そのテーブルは Phase 2 で作られる。
             */
            agent: components["schemas"]["AgentInfo"] | null;
            is_active: boolean;
            /**
             * Format: date-time
             * @description 一度もログインしていなければ `null`。
             */
            last_login_at: string | null;
            /**
             * @description `project_member` の行数。**アーカイブ済みプロジェクトも数える**
             *     （詳細画面の memberships と食い違わせないため）。
             */
            project_count: number;
            /** Format: date-time */
            created_at: string;
        };
        /**
         * @description エージェントの付帯情報（ApiDesign.md 6.1）。**Phase 1 では返らない**
         *     （対応する `agent` テーブルが Phase 2 で作られるため）。
         */
        AgentInfo: {
            client_kind: string;
            model_name: string;
            project_key: string;
            trust_level: number;
        };
        /** @description ユーザーの作成（ApiDesign.md 6.2）。 */
        CreateUserRequest: {
            /** @description 1〜60文字（`actor.display_name` の CHECK 制約と同じ）。前後の空白は落とす。 */
            display_name: string;
            /**
             * Format: email
             * @description 254文字以内（RFC 5321 4.5.3.1.3）。表示名付き（`山田 <a@example.com>`）は受け付けない。
             *     既に使われていれば `409 already_exists`。
             */
            email: string;
            /**
             * @description 省略時は `operator`。
             * @default operator
             * @enum {string}
             */
            system_role: "operator" | "administrator";
            /**
             * @description 省略時は `generate`（GuiDesign.md 5.6.1 の初期選択）。
             * @default generate
             * @enum {string}
             */
            password_mode: "generate" | "manual";
            /**
             * @description `password_mode=manual` のときのみ必須。12文字以上（Design.md 6.3）。
             *     `generate` のときに送られても無視する（モード切替でフォームに残った値を弾かない）。
             */
            password?: string | null;
            /**
             * @description 省略時は `true`（GuiDesign.md 5.6.1 のチェックボックスが既定でオン）。
             * @default true
             */
            must_change_password: boolean;
        };
        /**
         * @description 作成された利用者（ApiDesign.md 6.2 の 201）。一覧の要素（`UserListItem`）とは別で、
         *     作成直後に確定している値だけを返す。
         */
        CreatedUser: {
            /** @description ULID（`actor.id`）。 */
            id: string;
            /** @enum {string} */
            kind: "user";
            display_name: string;
            email: string;
            /** @enum {string} */
            system_role: "operator" | "administrator";
            is_active: boolean;
            /**
             * @description **この応答でのみ返る。** 再表示できず、監査ログにも残さない。
             *     形式は `<形容詞>-<名詞>-<4桁数字>`（例 `quiet-harbor-4172`）で、
             *     読み上げ・転記しやすい語句連結方式（ApiDesign.md 6.2）。
             *     `password_mode=manual` のときは `null`（呼び出し側が既に平文を持っているため）。
             */
            generated_password: string | null;
        };
        /** @description 一覧の共通エンベロープ（ApiDesign.md 2.6）。 */
        ProjectList: {
            items: components["schemas"]["ProjectListItem"][];
            page: number;
            per_page: number;
            total: number;
            /** @description 切り上げ。総件数0のときは0。 */
            total_pages: number;
        };
        ProjectListItem: {
            id: string;
            /** @example my-app */
            key: string;
            name: string;
            description: string | null;
            /** @enum {string} */
            status: "active" | "archived";
            ticket_count: number;
            /** @description `ticket.closed_at IS NOT NULL` の件数（DbDesign.md 6.6）。 */
            closed_count: number;
            /**
             * @description `closed_count / ticket_count`。**サーバで計算する**（定義をフロントに散らさないため）。
             *     `ticket_count = 0` のときは `0`（null にしない。ApiDesign.md 5.1）。
             * @example 0.75
             */
            progress: number;
            /**
             * @description 当該プロジェクトでのプロジェクトロール。
             *     **メンバーでないアドミニストレータでは null**（5.1 の「管理者は全件」で返る行）。
             * @example project_admin
             */
            my_role: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        CreateProjectRequest: {
            /**
             * @description `^[a-z0-9][a-z0-9-]{1,19}$`。予約語（`admin` `api` `mcp` `login` `logout`
             *     `me` `p` `new` `projects` `static` `assets` `check-key`）は使えない。
             *     **作成後は変更不可。**
             * @example my-app
             */
            key: string;
            name: string;
            description?: string;
            /**
             * @description 実体は DbDesign.md 7.4 のテンプレート。
             * @default simple
             * @enum {string}
             */
            workflow_template: "simple" | "with_review" | "with_approval";
        };
        /**
         * @description `PATCH /projects/:key` の本文（ApiDesign.md 5.5）。**送られたフィールドだけを
         *     更新する**ため required は無い。`key` は受け付けず、送ると 422
         *     （`details[].code` が `immutable_field`）になる。
         */
        UpdateProjectRequest: {
            name?: string;
            /**
             * @description `null` を明示すると説明を消す。フィールドごと送らなければ据え置く。
             *     空文字は `null` と同じ扱い（`POST /projects` に合わせる）。
             */
            description?: string | null;
            /**
             * @description `project.settings`（jsonb）をそのまま置き換える。**部分更新ではない**ので、
             *     取得した値を保持し、変更するキーだけ差し替えて全体を送ること。
             *
             *     サーバは JSON オブジェクトであることしか検証しない。Phase 1 の画面が
             *     使うキーは `repositories` のみで、構造の正本は DbDesign.md 6.4 にある。
             */
            settings?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description `POST /projects`・`GET /projects/:key`・`PATCH /projects/:key`・
         *     archive / unarchive が返す共通の本体（ApiDesign.md 5.4）。
         *     **どれか1つだけ形を変えない。**
         */
        ProjectDetail: {
            id: string;
            key: string;
            name: string;
            description: string | null;
            /** @enum {string} */
            status: "active" | "archived";
            /** @description `project.workflow_id` が NULL のときは null。 */
            workflow: components["schemas"]["Workflow"] | null;
            members: components["schemas"]["ProjectMember"][];
            /** @description メンバーでないアドミニストレータでは null。 */
            my_role: string | null;
            /**
             * @description 当該プロジェクトでの実効権限
             *     （システムロール ∪ プロジェクトロール ∩ スコープ。Design.md 6.4.1）。
             */
            my_permissions: string[];
            /**
             * @description `project.settings`（jsonb）をそのまま返す。Phase 1 の画面が使うキーは
             *     `repositories` のみで、構造の正本は DbDesign.md 6.4 にある。
             */
            settings: {
                [key: string]: unknown;
            };
            /** @description 楽観ロック用（ApiDesign.md 2.8）。作成直後は 1。 */
            version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Workflow: {
            id: string;
            name: string;
            /** @description `sort_order` の昇順。 */
            statuses: components["schemas"]["WorkflowStatus"][];
        };
        WorkflowStatus: {
            /** @example todo */
            key: string;
            /** @example 未着手 */
            name: string;
            /** @enum {string} */
            category: "todo" | "in_progress" | "review" | "done";
            sort_order: number;
            /** @description 人間の承認を要するステータス（Requirements.md 10.10.4）。 */
            requires_human_approval: boolean;
            /** @description エージェントが遷移させてよいか。 */
            is_agent_reachable: boolean;
        };
        ProjectMember: {
            actor_id: string;
            /**
             * @description エージェントもプロジェクトのメンバーになれる（DbDesign.md 6.3）。
             * @enum {string}
             */
            kind: "user" | "agent" | "system";
            display_name: string;
            /**
             * @description `app_user.email`（DbDesign.md 6.2）。**エージェントとシステムアクターは
             *     `app_user` の行を持たないため null**。キーは常に返す。
             * @example tanaka@example.com
             */
            email: string | null;
            /** @example project_admin */
            role: string;
            /** Format: date-time */
            joined_at: string;
        };
        CheckKeyResult: {
            key: string;
            available: boolean;
            /**
             * @description `available: false` のときだけ現れる（ApiDesign.md 5.2）。
             * @enum {string}
             */
            reason?: "reserved" | "already_exists" | "invalid_format";
        };
        Health: {
            /** @constant */
            status: "OK";
            /** @description `PB_HEALTH_SHOW_VERSION=true` のときだけ出る（既定は出ない）。 */
            version?: string;
        };
        /**
         * @description 全エンドポイント共通のエラー形式（ApiDesign.md 2.5）。
         *     `message` はそのまま画面に出せる日本語。**フロントで文言を組み立てない。**
         */
        Error: {
            error: {
                code: components["schemas"]["ErrorCode"];
                /** @example メールアドレスまたはパスワードが正しくありません */
                message: string;
                /** @description フィールド単位のエラー。フォームの入力欄に紐づける。 */
                details?: components["schemas"]["ErrorDetail"][];
                /**
                 * @description 再試行までの秒数。`account_locked` と `rate_limited` で返す。
                 *     同じ値が `Retry-After` ヘッダにも入る。
                 */
                retry_after_sec?: number;
                /**
                 * @description `audit_log.request_id`（DbDesign.md 6.8）および構造化ログ
                 *     （Design.md 10.1）と突き合わせられる。
                 * @example 01K2F8QW3H7YRJ4M5N6P7Q8R9S
                 */
                request_id: string;
            };
        };
        ErrorDetail: {
            field: string;
            code: string;
            message: string;
        };
        /**
         * @description ApiDesign.md 2.5.1 の15コード。
         * @enum {string}
         */
        ErrorCode: "bad_request" | "unauthenticated" | "invalid_credentials" | "forbidden" | "csrf_failed" | "not_found" | "method_not_allowed" | "conflict" | "already_exists" | "last_administrator" | "self_modification_forbidden" | "validation_failed" | "account_locked" | "rate_limited" | "internal_error";
    };
    responses: {
        /** @description 形式不正・パースエラー（`bad_request`）。 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 未認証・トークン失効・アカウント無効（`unauthenticated`）。 */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 権限不足（`forbidden`）。`audit_log` に `permission.denied` が残る（Design.md 6.4.5）。 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description CSRF トークンの不一致（`csrf_failed`）。Cookie 欠落・ヘッダ欠落・不一致を区別しない。 */
        CSRFFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 入力値の検証エラー（`validation_failed`）。`details` を伴う。 */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description 切り替え後のプロジェクト（5.4 と同形式）。**既にその状態でも 200 を返す**
         *     （ApiDesign.md 5.6 の冪等）。
         */
        ProjectStatusChanged: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProjectDetail"];
            };
        };
        /** @description レート制限（`rate_limited`。ApiDesign.md 2.9）。 */
        RateLimited: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description サーバ内部エラー（`internal_error`）。 */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description プロジェクトキー（ULID ではない。ApiDesign.md 5.4）。URL・チケット番号と
         *     一致させ、開発時のデバッグを容易にするため。
         */
        ProjectKey: string;
        /**
         * @description `pb_csrf` Cookie と同じ値を送る（double submit。ApiDesign.md 2.4）。
         *     Cookie 認証の状態変更系でのみ要求する。Bearer 認証では不要。
         */
        csrfToken: string;
    };
    requestBodies: never;
    headers: {
        /** @description 再試行までの秒数。`error.retry_after_sec` と同じ値（ApiDesign.md 2.5）。 */
        RetryAfter: number;
        /** @description 窓あたりの上限回数（ApiDesign.md 2.9）。 */
        XRateLimitLimit: number;
        /** @description 窓の残り回数（ApiDesign.md 2.9）。 */
        XRateLimitRemaining: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /**
             * @description 認証成功。`pb_session` と `pb_csrf` の2つの Cookie を発行する。
             *     **両者の Max-Age は揃える**（ApiDesign.md 3.1）。
             */
            200: {
                headers: {
                    /**
                     * @description ```
                     *     pb_session=pb_sess_...; HttpOnly; SameSite=Lax; Path=/; Max-Age=1209600
                     *     pb_csrf=...; SameSite=Lax; Path=/; Max-Age=1209600
                     *     ```
                     *     `Secure` は設定 `PB_COOKIE_SECURE` が true のときに付く。
                     */
                    "Set-Cookie"?: string;
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            /**
             * @description 認証失敗。**ユーザー不在・誤パスワード・アカウント無効を区別しない**
             *     （`invalid_credentials`）。
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            /**
             * @description ログイン失敗が続いたことによるロック中（`account_locked`）。
             *     残り秒数を `error.retry_after_sec` と `Retry-After` ヘッダに入れる。
             *     **閾値に達した回から**この応答になる（ApiDesign.md 3.1）。
             */
            423: {
                headers: {
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 失効済み。`pb_session` と `pb_csrf` を削除する Set-Cookie を返す。 */
            204: {
                headers: {
                    /** @description 2つの Cookie を `Max-Age=-1` で削除する。 */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CSRFFailed"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 認証中のアクター。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                /** @description 既定は `active`。 */
                status?: "active" | "archived" | "all";
                sort?: "name" | "key" | "updated_at" | "ticket_count" | "progress";
                order?: "asc" | "desc";
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 1ページ分のプロジェクト。 */
            200: {
                headers: {
                    /**
                     * @description 弱い検証子 `W/"proj-<件数>-<MAX(updated_at) のナノ秒>"`（ApiDesign.md 2.7）。
                     *     **Phase 1 では `If-None-Match` を解釈しない**（304 を返さない）。
                     */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description 作成された。応答は `GET /projects/:key` と同形式（5.4）。 */
            201: {
                headers: {
                    /** @description `/api/v1/projects/<key>` */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            /** @description 権限不足（`forbidden`）または CSRF トークンの不一致（`csrf_failed`）。 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description プロジェクトキーが既に使われている（`already_exists`。ApiDesign.md 5.3）。 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    checkProjectKey: {
        parameters: {
            query: {
                key: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 判定結果。**使えない場合も 200 で返す**（エラーではない）。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckKeyResult"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description プロジェクトキー（ULID ではない。ApiDesign.md 5.4）。URL・チケット番号と
                 *     一致させ、開発時のデバッグを容易にするため。
                 */
                key: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description プロジェクトの詳細。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            /**
             * @description プロジェクトが存在しない、または到達できない（`not_found`）。
             *     **両者を区別しない**（Design.md 6.4.5）。
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header: {
                /** @description 取得時の `version`。`"3"` のように引用符で囲む（RFC 9110 8.8.3）。 */
                "If-Match": string;
            };
            path: {
                /**
                 * @description プロジェクトキー（ULID ではない。ApiDesign.md 5.4）。URL・チケット番号と
                 *     一致させ、開発時のデバッグを容易にするため。
                 */
                key: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description 更新後のプロジェクト（5.4 と同形式）。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            /** @description 権限不足（`forbidden`）または CSRF トークンの不一致（`csrf_failed`）。 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description プロジェクトが存在しない、または到達できない（`not_found`）。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description `If-Match` が現在の `version` と一致しない（`conflict`。ApiDesign.md 2.8）。 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    archiveProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description プロジェクトキー（ULID ではない。ApiDesign.md 5.4）。URL・チケット番号と
                 *     一致させ、開発時のデバッグを容易にするため。
                 */
                key: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ProjectStatusChanged"];
            401: components["responses"]["Unauthenticated"];
            /** @description 権限不足（`forbidden`）または CSRF トークンの不一致（`csrf_failed`）。 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description プロジェクトが存在しない、または到達できない（`not_found`）。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    unarchiveProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description プロジェクトキー（ULID ではない。ApiDesign.md 5.4）。URL・チケット番号と
                 *     一致させ、開発時のデバッグを容易にするため。
                 */
                key: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ProjectStatusChanged"];
            401: components["responses"]["Unauthenticated"];
            /** @description 権限不足（`forbidden`）または CSRF トークンの不一致（`csrf_failed`）。 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description プロジェクトが存在しない、または到達できない（`not_found`）。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /** @description 既定は `all`。 */
                kind?: "user" | "agent" | "all";
                /** @description 既定は `all`。**真偽値ではなく3値の文字列**（未指定と false を区別する）。 */
                is_active?: "true" | "false" | "all";
                /**
                 * @description 表示名・メールアドレス・**ロールの表示名**の部分一致。ロールは `role.display_name`
                 *     （「アドミニストレータ」「オペレータ」）と比べる。**画面に出ないキー
                 *     （`administrator`）は対象にしない。** `%` と `_` はサーバ側でエスケープするため
                 *     ワイルドカードとしては働かない。**画面は検索欄を常時表示する**（GuiDesign.md 5.6）。
                 */
                q?: string;
                /**
                 * @description `system_role` は `role.sort_order` の順（オペレータ → アドミニストレータ）で、
                 *     表示名の五十音順ではない。**ロールを持たない行（エージェント）は昇順・降順とも末尾。**
                 *     `is_active` の昇順は無効が先（`false < true`）。
                 */
                sort?: "display_name" | "email" | "system_role" | "is_active" | "last_login_at" | "created_at";
                /**
                 * @description 既定は `asc`。名簿は昇順で読むためで、他の一覧（`GET /projects` は `desc`）とは
                 *     既定が違う。
                 */
                order?: "asc" | "desc";
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 1ページ分のユーザー。 */
            200: {
                headers: {
                    /**
                     * @description 弱い検証子 `W/"user-<件数>-<MAX(updated_at) のナノ秒>"`（ApiDesign.md 2.7）。
                     *     `updated_at` は `actor` と `app_user` の新しいほうを採る。
                     *     **Phase 1 では `If-None-Match` を解釈しない**（304 を返さない）。
                     */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description 作成された。 */
            201: {
                headers: {
                    /** @description `/api/v1/admin/users/<id>` */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedUser"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            /** @description 権限不足（`forbidden`）または CSRF トークンの不一致（`csrf_failed`）。 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description メールアドレスが既に使われている（`already_exists`。ApiDesign.md 6.2）。 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    healthcheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 常に `{"status":"OK"}`。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
