/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログイン
         * @description メールアドレスとパスワードで認証し、セッションを発行する（ApiDesign.md 3.1）。
         *
         *     応答本文は `GET /api/v1/me` と同じ内容を含む。ログイン直後に必ず権限が必要になるため、
         *     往復を1回減らしている。
         *
         *     認証不要。IPあたり 10回/分のレート制限が掛かる（ApiDesign.md 2.9）。
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログアウト
         * @description 現在のセッショントークンを失効させ（`revoked_at` を設定）、Cookie を削除する
         *     （ApiDesign.md 3.2）。Cookie 認証のため `X-PB-CSRF` が必要（2.4）。
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 自分自身と実効権限
         * @description 認証中のアクターと実効権限を返す（ApiDesign.md 4.1）。
         *
         *     `permissions` はシステムロール由来の実効権限、`projects[].permissions` は
         *     当該プロジェクトでの実効権限（システムロール ∪ プロジェクトロール ∩ スコープ。
         *     Design.md 6.4.1）。`projects[]` にはアーカイブ済みのプロジェクトも含む。
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthcheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ヘルスチェック
         * @description 監視・オーケストレータ用（ApiDesign.md 2.11）。**唯一 `/api/v1` の外にある。**
         *     認証・CSRF・レート制限・認可の対象外で、DBへは接続しない。
         */
        get: operations["healthcheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            /** @example tanaka@example.com */
            email: string;
            /** Format: password */
            password: string;
        };
        /** @description `POST /auth/login` と `GET /me` が返す共通の本体。**片方だけ形を変えない。** */
        Session: {
            actor: components["schemas"]["Actor"];
            /**
             * @description システムロール由来の実効権限。権限0件は空配列で表す。
             * @example [
             *       "project.view",
             *       "ticket.view"
             *     ]
             */
            permissions: string[];
            /** @description 所属プロジェクトと、そこでの実効権限。`key` の昇順。 */
            projects: components["schemas"]["SessionProject"][];
            /**
             * Format: date-time
             * @description 現在のトークンの有効期限。無期限の API トークンでは null。
             */
            expires_at: string | null;
        };
        Actor: {
            /**
             * @description ULID 26文字。
             * @example 01K2F8QW3H7YRJ4M5N6P7Q8R9S
             */
            id: string;
            /** @enum {string} */
            kind: "user" | "agent";
            display_name: string;
            /** @description エージェントは null（ApiDesign.md 6.1。フィールド自体は省略しない）。 */
            email: string | null;
            /**
             * @description 同上。
             * @enum {string|null}
             */
            system_role: "administrator" | "operator" | null;
            /** @example ja */
            locale: string | null;
            /** @example Asia/Tokyo */
            timezone: string | null;
            /** @description true のときフロントはパスワード変更画面へ誘導する（ApiDesign.md 3.1）。 */
            must_change_password: boolean;
        };
        SessionProject: {
            id: string;
            /** @example my-app */
            key: string;
            name: string;
            /**
             * @description プロジェクトロールのキー（DbDesign.md 7.3）。
             * @example project_admin
             */
            role: string;
            /** @description 当該プロジェクトでの実効権限。 */
            permissions: string[];
        };
        Health: {
            /** @constant */
            status: "OK";
            /** @description `PB_HEALTH_SHOW_VERSION=true` のときだけ出る（既定は出ない）。 */
            version?: string;
        };
        /**
         * @description 全エンドポイント共通のエラー形式（ApiDesign.md 2.5）。
         *     `message` はそのまま画面に出せる日本語。**フロントで文言を組み立てない。**
         */
        Error: {
            error: {
                code: components["schemas"]["ErrorCode"];
                /** @example メールアドレスまたはパスワードが正しくありません */
                message: string;
                /** @description フィールド単位のエラー。フォームの入力欄に紐づける。 */
                details?: components["schemas"]["ErrorDetail"][];
                /**
                 * @description 再試行までの秒数。`account_locked` と `rate_limited` で返す。
                 *     同じ値が `Retry-After` ヘッダにも入る。
                 */
                retry_after_sec?: number;
                /**
                 * @description `audit_log.request_id`（DbDesign.md 6.8）および構造化ログ
                 *     （Design.md 10.1）と突き合わせられる。
                 * @example 01K2F8QW3H7YRJ4M5N6P7Q8R9S
                 */
                request_id: string;
            };
        };
        ErrorDetail: {
            field: string;
            code: string;
            message: string;
        };
        /**
         * @description ApiDesign.md 2.5.1 の14コード。
         * @enum {string}
         */
        ErrorCode: "bad_request" | "unauthenticated" | "invalid_credentials" | "forbidden" | "csrf_failed" | "not_found" | "method_not_allowed" | "conflict" | "last_administrator" | "self_modification_forbidden" | "validation_failed" | "account_locked" | "rate_limited" | "internal_error";
    };
    responses: {
        /** @description 形式不正・パースエラー（`bad_request`）。 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 未認証・トークン失効・アカウント無効（`unauthenticated`）。 */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description CSRF トークンの不一致（`csrf_failed`）。Cookie 欠落・ヘッダ欠落・不一致を区別しない。 */
        CSRFFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 入力値の検証エラー（`validation_failed`）。`details` を伴う。 */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description レート制限（`rate_limited`。ApiDesign.md 2.9）。 */
        RateLimited: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description サーバ内部エラー（`internal_error`）。 */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description 再試行までの秒数。`error.retry_after_sec` と同じ値（ApiDesign.md 2.5）。 */
        RetryAfter: number;
        /** @description 窓あたりの上限回数（ApiDesign.md 2.9）。 */
        XRateLimitLimit: number;
        /** @description 窓の残り回数（ApiDesign.md 2.9）。 */
        XRateLimitRemaining: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /**
             * @description 認証成功。`pb_session` と `pb_csrf` の2つの Cookie を発行する。
             *     **両者の Max-Age は揃える**（ApiDesign.md 3.1）。
             */
            200: {
                headers: {
                    /**
                     * @description ```
                     *     pb_session=pb_sess_...; HttpOnly; SameSite=Lax; Path=/; Max-Age=1209600
                     *     pb_csrf=...; SameSite=Lax; Path=/; Max-Age=1209600
                     *     ```
                     *     `Secure` は設定 `PB_COOKIE_SECURE` が true のときに付く。
                     */
                    "Set-Cookie"?: string;
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            /**
             * @description 認証失敗。**ユーザー不在・誤パスワード・アカウント無効を区別しない**
             *     （`invalid_credentials`）。
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            /**
             * @description ログイン失敗が続いたことによるロック中（`account_locked`）。
             *     残り秒数を `error.retry_after_sec` と `Retry-After` ヘッダに入れる。
             *     **閾値に達した回から**この応答になる（ApiDesign.md 3.1）。
             */
            423: {
                headers: {
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 失効済み。`pb_session` と `pb_csrf` を削除する Set-Cookie を返す。 */
            204: {
                headers: {
                    /** @description 2つの Cookie を `Max-Age=-1` で削除する。 */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CSRFFailed"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 認証中のアクター。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    healthcheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 常に `{"status":"OK"}`。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
